### ISSUE TITLE
Suche funktioniert nicht

### ISSUE THREAD

**Issue by TobiasNx** [dini-ag-kim/hcrt#10]
Wenn man "Lern" eintippt, dann wird "Lernspiel" nicht angezeigt.

**Comment by sroertgen** [comment]
Wir arbeiten dran :)

https://github.com/skohub-io/skohub-vocabs/issues/127

**Comment by acka47** [comment]
https://github.com/skohub-io/skohub-vocabs/issues/127 ist nun implementiert und HCRT wurde neu gebaut. Eingabe von "Lern" in die deutschsprachige Sicht gibt nun Ergebnisse. Closing.
