### ISSUE TITLE
Ergänzung um H5P-Elemente

### ISSUE THREAD

**Issue by s-prepens** [dini-ag-kim/hcrt#14]
Vorschlag zur Ergänzung bei [HCRT](https://skohub.io/dini-ag-kim/hcrt/heads/master/w3id.org/kim/hcrt/index.de.html)/[Medientypen von ORCA.nrw](https://skohub.io/orca.nrw/orca-vocabs/heads/main/w3id.org/orca.nrw/medientypen/index.de.html) um Ressourcentyp "H5P-Element"

**Comment by acka47** [comment]
Danke für den Voschlag, @s-prepens . Ich bin mir nicht sicher, ob wir das aufnehmen sollten, da es sich ja um ein Format handelt, nicht um einen speziellen Ressourcentyp handelt. (Ein H5P-Dokument kann ja selbst verschiedene Ressourcentypen enthalten/sein: Lernkontrolle, Tonaufnahme, Übung, Lernspiel, Karte, Fragebogen etc.)

M.E. wäre das in AMB am besten unter `encoding.encodingFormat` untergebracht. Leider gibt es aber (noch) keinen [IANA media type](https://www.iana.org/assignments/media-types/media-types.xhtml) für H5P. Wir sollten das mal beim nächsten Treffen besprechen.

**Comment by acka47** [comment]
Im [Treffen vom 2022-01-11](https://pad.gwdg.de/s/2022-01-11-kim-oer#Auszeichnung-von-H5P-Ressourcen) haben wir beschlossen, dass die beste Lösung die Angabe eines H5P Media Types wäre. Leider gibt es diesen noch nicht in der IANA Registry.

Deshalb habe ich im Februar mal im H5P-Forum nachgefragt, ob Interesse daran besteht, einen solchen Media Type zu registrieren, siehe https://h5p.org/node/1249245. Leider kam bis heute keine Antwort. Wir sollten also am ebsten selbst probieren, den Media Type zu registrieren.

**Comment by kulla** [comment]
> Leider kam bis heute keine Antwort.

Sollte keine Antwort kommen, könnten wir in AMB den Wert `application/h5p+zip` explizit festlegen...

**Comment by acka47** [comment]
> Sollte keine Antwort kommen, könnten wir in AMB den Wert application/h5p+zip explizit festlegen...

Du hast Recht, dass wir hier vielleicht besser nicht auf eine Registrierung warten sollten. Dann sollten wir den Media Type aber glaube ich als unregistriert markieren, also `application/x.h5p+zip`. (Die Ansicht resultiert aus einer kurzen SWebsche und insbesondere dem, was in Wikipedia unter https://en.wikipedia.org/wiki/Media_type#Unregistered_tree steht.)

**Comment by acka47** [comment]
> Die Ansicht resultiert aus einer kurzen Websuche und insbesondere dem, was in Wikipedia unter https://en.wikipedia.org/wiki/Media_type#Unregistered_tree steht.

Hätte ich das auch mal zu Ende gelesen, dann wär mir klar, dass `x.` nicht genutzt werden soll. Ich mache mal besser Feierabend.

**Comment by acka47** [comment]
Ich glaube, der "vendor tree", wäre die richtige Wahl: `application/vnd.h5p+zip`. Das müsste man aber am besten auch registrieren, was wir – wenn ich das richtig sehe – selbst machen könnten. Das enbtsprechende Formular ist hier: https://www.iana.org/form/media-types

Um das auszufüllen, müssten wir uns aber durch ein paar RFCs arbeiten...

**Comment by acka47** [comment]
Ich habe jetzt https://github.com/dini-ag-kim/amb/issues/146 geöffnet und mache das hier zu.
